name: M3U Generator

permissions:
  contents: write

on:
  schedule:
    - cron: '0 */3 * * *'   # Every 6 hours
  push:
    branches:
      - RenjithVR4-patch-1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Run Generator
        run: |
          chmod +x autorun.sh
          ./autorun.sh

      - name: Commit Changes
        run: |
          git add -A
          git diff --cached --quiet || git commit -m "Auto-update M3U links"

      - name: Push Changes
        run: |
          git push
